
os: osx
osx_image: xcode12.5
language: swift
script: xcodebuild clean build test -project TheMovieDB/TheMovieDB.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES

