
os: osx
osx_image: xcode12.5
language: swift
script:
    - xcodebuild clean build test -project TheMovieDB/TheMovieDB.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    - xcodebuild clean build test -project TheMovieDB/TheMovieDB.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=iOS Simulator,OS=14.5,name=iPhone 11 Pro max" ONLY_ACTIVE_ARCH=YES

